//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace SLEWebService.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SLEWebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Responce))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    public partial class SLEWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback S1_001OperationCompleted;
        
        private System.Threading.SendOrPostCallback S1_004OperationCompleted;
        
        private System.Threading.SendOrPostCallback S1_005OperationCompleted;
        
        private System.Threading.SendOrPostCallback S1_009OperationCompleted;
        
        private System.Threading.SendOrPostCallback S1_018OperationCompleted;
        
        private System.Threading.SendOrPostCallback S1_019OperationCompleted;
        
        private System.Threading.SendOrPostCallback S1_020OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SLEWebService() {
            this.Url = global::SLEWebService.Properties.Settings.Default.SLEWebService_WebReference_SLEWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event S1_001CompletedEventHandler S1_001Completed;
        
        /// <remarks/>
        public event S1_004CompletedEventHandler S1_004Completed;
        
        /// <remarks/>
        public event S1_005CompletedEventHandler S1_005Completed;
        
        /// <remarks/>
        public event S1_009CompletedEventHandler S1_009Completed;
        
        /// <remarks/>
        public event S1_018CompletedEventHandler S1_018Completed;
        
        /// <remarks/>
        public event S1_019CompletedEventHandler S1_019Completed;
        
        /// <remarks/>
        public event S1_020CompletedEventHandler S1_020Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/S1_001", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderCommitResp S1_001(OrderCommitReq orderCommitReq) {
            object[] results = this.Invoke("S1_001", new object[] {
                        orderCommitReq});
            return ((OrderCommitResp)(results[0]));
        }
        
        /// <remarks/>
        public void S1_001Async(OrderCommitReq orderCommitReq) {
            this.S1_001Async(orderCommitReq, null);
        }
        
        /// <remarks/>
        public void S1_001Async(OrderCommitReq orderCommitReq, object userState) {
            if ((this.S1_001OperationCompleted == null)) {
                this.S1_001OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS1_001OperationCompleted);
            }
            this.InvokeAsync("S1_001", new object[] {
                        orderCommitReq}, this.S1_001OperationCompleted, userState);
        }
        
        private void OnS1_001OperationCompleted(object arg) {
            if ((this.S1_001Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S1_001Completed(this, new S1_001CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/S1_004", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderExecuteResultResp S1_004(OrderExecuteResultReq orderExecuteResultReq) {
            object[] results = this.Invoke("S1_004", new object[] {
                        orderExecuteResultReq});
            return ((OrderExecuteResultResp)(results[0]));
        }
        
        /// <remarks/>
        public void S1_004Async(OrderExecuteResultReq orderExecuteResultReq) {
            this.S1_004Async(orderExecuteResultReq, null);
        }
        
        /// <remarks/>
        public void S1_004Async(OrderExecuteResultReq orderExecuteResultReq, object userState) {
            if ((this.S1_004OperationCompleted == null)) {
                this.S1_004OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS1_004OperationCompleted);
            }
            this.InvokeAsync("S1_004", new object[] {
                        orderExecuteResultReq}, this.S1_004OperationCompleted, userState);
        }
        
        private void OnS1_004OperationCompleted(object arg) {
            if ((this.S1_004Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S1_004Completed(this, new S1_004CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/S1_005", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OrderExecuteFaultResp S1_005(OrderExecuteFaultReq orderExecuteFaultReq) {
            object[] results = this.Invoke("S1_005", new object[] {
                        orderExecuteFaultReq});
            return ((OrderExecuteFaultResp)(results[0]));
        }
        
        /// <remarks/>
        public void S1_005Async(OrderExecuteFaultReq orderExecuteFaultReq) {
            this.S1_005Async(orderExecuteFaultReq, null);
        }
        
        /// <remarks/>
        public void S1_005Async(OrderExecuteFaultReq orderExecuteFaultReq, object userState) {
            if ((this.S1_005OperationCompleted == null)) {
                this.S1_005OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS1_005OperationCompleted);
            }
            this.InvokeAsync("S1_005", new object[] {
                        orderExecuteFaultReq}, this.S1_005OperationCompleted, userState);
        }
        
        private void OnS1_005OperationCompleted(object arg) {
            if ((this.S1_005Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S1_005Completed(this, new S1_005CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/S1_009", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HeartBeatResp S1_009(HeartBeatReq heartBeatReq) {
            object[] results = this.Invoke("S1_009", new object[] {
                        heartBeatReq});
            return ((HeartBeatResp)(results[0]));
        }
        
        /// <remarks/>
        public void S1_009Async(HeartBeatReq heartBeatReq) {
            this.S1_009Async(heartBeatReq, null);
        }
        
        /// <remarks/>
        public void S1_009Async(HeartBeatReq heartBeatReq, object userState) {
            if ((this.S1_009OperationCompleted == null)) {
                this.S1_009OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS1_009OperationCompleted);
            }
            this.InvokeAsync("S1_009", new object[] {
                        heartBeatReq}, this.S1_009OperationCompleted, userState);
        }
        
        private void OnS1_009OperationCompleted(object arg) {
            if ((this.S1_009Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S1_009Completed(this, new S1_009CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/S1_018", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SnapQRCodePrePayURLQueryResp S1_018(SnapQRCodePrePayURLQueryReq snapQRCodePrePayURLQueryReq) {
            object[] results = this.Invoke("S1_018", new object[] {
                        snapQRCodePrePayURLQueryReq});
            return ((SnapQRCodePrePayURLQueryResp)(results[0]));
        }
        
        /// <remarks/>
        public void S1_018Async(SnapQRCodePrePayURLQueryReq snapQRCodePrePayURLQueryReq) {
            this.S1_018Async(snapQRCodePrePayURLQueryReq, null);
        }
        
        /// <remarks/>
        public void S1_018Async(SnapQRCodePrePayURLQueryReq snapQRCodePrePayURLQueryReq, object userState) {
            if ((this.S1_018OperationCompleted == null)) {
                this.S1_018OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS1_018OperationCompleted);
            }
            this.InvokeAsync("S1_018", new object[] {
                        snapQRCodePrePayURLQueryReq}, this.S1_018OperationCompleted, userState);
        }
        
        private void OnS1_018OperationCompleted(object arg) {
            if ((this.S1_018Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S1_018Completed(this, new S1_018CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/S1_019", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SnapQRCodePayResultQueryResp S1_019(SnapQRCodePayResultQueryReq snapQRCodePayResultQueryReq) {
            object[] results = this.Invoke("S1_019", new object[] {
                        snapQRCodePayResultQueryReq});
            return ((SnapQRCodePayResultQueryResp)(results[0]));
        }
        
        /// <remarks/>
        public void S1_019Async(SnapQRCodePayResultQueryReq snapQRCodePayResultQueryReq) {
            this.S1_019Async(snapQRCodePayResultQueryReq, null);
        }
        
        /// <remarks/>
        public void S1_019Async(SnapQRCodePayResultQueryReq snapQRCodePayResultQueryReq, object userState) {
            if ((this.S1_019OperationCompleted == null)) {
                this.S1_019OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS1_019OperationCompleted);
            }
            this.InvokeAsync("S1_019", new object[] {
                        snapQRCodePayResultQueryReq}, this.S1_019OperationCompleted, userState);
        }
        
        private void OnS1_019OperationCompleted(object arg) {
            if ((this.S1_019Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S1_019Completed(this, new S1_019CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/S1_020", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SnapQRCodeTakeOrderQueryResp S1_020(SnapQRCodeTakeOrderQueryReq snapQRCodeTakeOrderQueryReq) {
            object[] results = this.Invoke("S1_020", new object[] {
                        snapQRCodeTakeOrderQueryReq});
            return ((SnapQRCodeTakeOrderQueryResp)(results[0]));
        }
        
        /// <remarks/>
        public void S1_020Async(SnapQRCodeTakeOrderQueryReq snapQRCodeTakeOrderQueryReq) {
            this.S1_020Async(snapQRCodeTakeOrderQueryReq, null);
        }
        
        /// <remarks/>
        public void S1_020Async(SnapQRCodeTakeOrderQueryReq snapQRCodeTakeOrderQueryReq, object userState) {
            if ((this.S1_020OperationCompleted == null)) {
                this.S1_020OperationCompleted = new System.Threading.SendOrPostCallback(this.OnS1_020OperationCompleted);
            }
            this.InvokeAsync("S1_020", new object[] {
                        snapQRCodeTakeOrderQueryReq}, this.S1_020OperationCompleted, userState);
        }
        
        private void OnS1_020OperationCompleted(object arg) {
            if ((this.S1_020Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.S1_020Completed(this, new S1_020CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCommitReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string paymentCodeField;
        
        private string msisdnField;
        
        private string iccidField;
        
        private string serviceIdField;
        
        private string paymentVendorField;
        
        private string pickupStationCodeField;
        
        private string getOffStationCodeField;
        
        private string singleTicketPriceField;
        
        private string singleTicketNumField;
        
        private string singleTicketTypeField;
        
        /// <remarks/>
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
            }
        }
        
        /// <remarks/>
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string paymentCode {
            get {
                return this.paymentCodeField;
            }
            set {
                this.paymentCodeField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
            }
        }
        
        /// <remarks/>
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string paymentVendor {
            get {
                return this.paymentVendorField;
            }
            set {
                this.paymentVendorField = value;
            }
        }
        
        /// <remarks/>
        public string pickupStationCode {
            get {
                return this.pickupStationCodeField;
            }
            set {
                this.pickupStationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string getOffStationCode {
            get {
                return this.getOffStationCodeField;
            }
            set {
                this.getOffStationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string singleTicketPrice {
            get {
                return this.singleTicketPriceField;
            }
            set {
                this.singleTicketPriceField = value;
            }
        }
        
        /// <remarks/>
        public string singleTicketNum {
            get {
                return this.singleTicketNumField;
            }
            set {
                this.singleTicketNumField = value;
            }
        }
        
        /// <remarks/>
        public string singleTicketType {
            get {
                return this.singleTicketTypeField;
            }
            set {
                this.singleTicketTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SnapQRCodeTakeOrderQueryReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SnapQRCodePayResultQueryReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SnapQRCodePrePayURLQueryReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HeartBeatReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteFaultReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteResultReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderCommitReq))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Request {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SnapQRCodeTakeOrderQueryResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SnapQRCodePayResultQueryResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SnapQRCodePrePayURLQueryResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HeartBeatResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteFaultResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteResultResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderCommitResp))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Responce {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SnapQRCodeTakeOrderQueryResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        private string paymentAccountField;
        
        private string orderNoField;
        
        private string pickupStationCodeField;
        
        private string getOffStationCodeField;
        
        private string singleTicketPriceField;
        
        private string singleTicketNumField;
        
        private string singleTicketTypeField;
        
        private string deviceIdField;
        
        private string userNameField;
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string paymentAccount {
            get {
                return this.paymentAccountField;
            }
            set {
                this.paymentAccountField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string pickupStationCode {
            get {
                return this.pickupStationCodeField;
            }
            set {
                this.pickupStationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string getOffStationCode {
            get {
                return this.getOffStationCodeField;
            }
            set {
                this.getOffStationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string singleTicketPrice {
            get {
                return this.singleTicketPriceField;
            }
            set {
                this.singleTicketPriceField = value;
            }
        }
        
        /// <remarks/>
        public string singleTicketNum {
            get {
                return this.singleTicketNumField;
            }
            set {
                this.singleTicketNumField = value;
            }
        }
        
        /// <remarks/>
        public string singleTicketType {
            get {
                return this.singleTicketTypeField;
            }
            set {
                this.singleTicketTypeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SnapQRCodePayResultQueryResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private string paymentDateField;
        
        private string amountField;
        
        private string paymentAccountField;
        
        private string paymentResultField;
        
        private string paymentDescField;
        
        private string userNameField;
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string paymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string paymentAccount {
            get {
                return this.paymentAccountField;
            }
            set {
                this.paymentAccountField = value;
            }
        }
        
        /// <remarks/>
        public string paymentResult {
            get {
                return this.paymentResultField;
            }
            set {
                this.paymentResultField = value;
            }
        }
        
        /// <remarks/>
        public string paymentDesc {
            get {
                return this.paymentDescField;
            }
            set {
                this.paymentDescField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SnapQRCodePrePayURLQueryResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private string deviceIdField;
        
        private string qrCodeField;
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string qrCode {
            get {
                return this.qrCodeField;
            }
            set {
                this.qrCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeartBeatResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteFaultResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteResultResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCommitResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        private string partnerNoField;
        
        private string orderNoField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string payTypeField;
        
        private string amountField;
        
        private string accountField;
        
        private string notifyUrlField;
        
        private string merchantCertField;
        
        private int timeoutField;
        
        /// <remarks/>
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
            }
        }
        
        /// <remarks/>
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string partnerNo {
            get {
                return this.partnerNoField;
            }
            set {
                this.partnerNoField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string payType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string notifyUrl {
            get {
                return this.notifyUrlField;
            }
            set {
                this.notifyUrlField = value;
            }
        }
        
        /// <remarks/>
        public string merchantCert {
            get {
                return this.merchantCertField;
            }
            set {
                this.merchantCertField = value;
            }
        }
        
        /// <remarks/>
        public int timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SnapQRCodeTakeOrderQueryReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string randomFactField;
        
        /// <remarks/>
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
            }
        }
        
        /// <remarks/>
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string randomFact {
            get {
                return this.randomFactField;
            }
            set {
                this.randomFactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SnapQRCodePayResultQueryReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private string qrCodeField;
        
        /// <remarks/>
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
            }
        }
        
        /// <remarks/>
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string qrCode {
            get {
                return this.qrCodeField;
            }
            set {
                this.qrCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SnapQRCodePrePayURLQueryReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        /// <remarks/>
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
            }
        }
        
        /// <remarks/>
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HeartBeatReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        /// <remarks/>
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
            }
        }
        
        /// <remarks/>
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteFaultReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private int takeSingleTicketNumField;
        
        private string faultOccurDateField;
        
        private string faultSlipSeqField;
        
        private string erroCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
            }
        }
        
        /// <remarks/>
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public int takeSingleTicketNum {
            get {
                return this.takeSingleTicketNumField;
            }
            set {
                this.takeSingleTicketNumField = value;
            }
        }
        
        /// <remarks/>
        public string faultOccurDate {
            get {
                return this.faultOccurDateField;
            }
            set {
                this.faultOccurDateField = value;
            }
        }
        
        /// <remarks/>
        public string faultSlipSeq {
            get {
                return this.faultSlipSeqField;
            }
            set {
                this.faultSlipSeqField = value;
            }
        }
        
        /// <remarks/>
        public string erroCode {
            get {
                return this.erroCodeField;
            }
            set {
                this.erroCodeField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteResultReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private int takeSingleTicketNumField;
        
        private string takeSingleTicketDateField;
        
        /// <remarks/>
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
            }
        }
        
        /// <remarks/>
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
            }
        }
        
        /// <remarks/>
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public int takeSingleTicketNum {
            get {
                return this.takeSingleTicketNumField;
            }
            set {
                this.takeSingleTicketNumField = value;
            }
        }
        
        /// <remarks/>
        public string takeSingleTicketDate {
            get {
                return this.takeSingleTicketDateField;
            }
            set {
                this.takeSingleTicketDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void S1_001CompletedEventHandler(object sender, S1_001CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class S1_001CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal S1_001CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderCommitResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderCommitResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void S1_004CompletedEventHandler(object sender, S1_004CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class S1_004CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal S1_004CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderExecuteResultResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderExecuteResultResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void S1_005CompletedEventHandler(object sender, S1_005CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class S1_005CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal S1_005CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OrderExecuteFaultResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OrderExecuteFaultResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void S1_009CompletedEventHandler(object sender, S1_009CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class S1_009CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal S1_009CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HeartBeatResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HeartBeatResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void S1_018CompletedEventHandler(object sender, S1_018CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class S1_018CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal S1_018CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SnapQRCodePrePayURLQueryResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SnapQRCodePrePayURLQueryResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void S1_019CompletedEventHandler(object sender, S1_019CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class S1_019CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal S1_019CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SnapQRCodePayResultQueryResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SnapQRCodePayResultQueryResp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void S1_020CompletedEventHandler(object sender, S1_020CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class S1_020CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal S1_020CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SnapQRCodeTakeOrderQueryResp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SnapQRCodeTakeOrderQueryResp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591