//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLEWebServiceTest.SLEWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SLEWebService.myWebService1Soap")]
    public interface myWebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S1_001", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Responce))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        SLEWebServiceTest.SLEWebService.OrderCommitResp S1_001(SLEWebServiceTest.SLEWebService.OrderCommitReq orderCommitReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S1_002", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Responce))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        SLEWebServiceTest.SLEWebService.QueryPaymentResultResp S1_002(SLEWebServiceTest.SLEWebService.QueryPaymentResultReq queryPaymentResultReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S1_006", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Responce))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        SLEWebServiceTest.SLEWebService.TicketVerificationResp S1_006(SLEWebServiceTest.SLEWebService.TicketVerificationReq ticketVerificationReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S1_003", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Responce))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        SLEWebServiceTest.SLEWebService.OrderExecuteBeginResp S1_003(SLEWebServiceTest.SLEWebService.OrderExecuteBeginReq orderExecuteBeginReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S1_004", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Responce))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        SLEWebServiceTest.SLEWebService.OrderExecuteResultResp S1_004(SLEWebServiceTest.SLEWebService.OrderExecuteResultReq orderExecuteResultReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/S1_005", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Responce))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Request))]
        SLEWebServiceTest.SLEWebService.OrderExecuteFaultResp S1_005(SLEWebServiceTest.SLEWebService.OrderExecuteFaultReq orderExecuteFaultReq);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCommitReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string paymentCodeField;
        
        private string msisdnField;
        
        private string iccidField;
        
        private string serviceIdField;
        
        private string paymentVendorField;
        
        private string pickupStationCodeField;
        
        private string getOffStationCodeField;
        
        private string singleTicketPriceField;
        
        private string singleTicketNumField;
        
        private string singleTicketTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
                this.RaisePropertyChanged("reqSysDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("operationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
                this.RaisePropertyChanged("channelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string paymentCode {
            get {
                return this.paymentCodeField;
            }
            set {
                this.paymentCodeField = value;
                this.RaisePropertyChanged("paymentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string paymentVendor {
            get {
                return this.paymentVendorField;
            }
            set {
                this.paymentVendorField = value;
                this.RaisePropertyChanged("paymentVendor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string pickupStationCode {
            get {
                return this.pickupStationCodeField;
            }
            set {
                this.pickupStationCodeField = value;
                this.RaisePropertyChanged("pickupStationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string getOffStationCode {
            get {
                return this.getOffStationCodeField;
            }
            set {
                this.getOffStationCodeField = value;
                this.RaisePropertyChanged("getOffStationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string singleTicketPrice {
            get {
                return this.singleTicketPriceField;
            }
            set {
                this.singleTicketPriceField = value;
                this.RaisePropertyChanged("singleTicketPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string singleTicketNum {
            get {
                return this.singleTicketNumField;
            }
            set {
                this.singleTicketNumField = value;
                this.RaisePropertyChanged("singleTicketNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string singleTicketType {
            get {
                return this.singleTicketTypeField;
            }
            set {
                this.singleTicketTypeField = value;
                this.RaisePropertyChanged("singleTicketType");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteFaultReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteResultReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteBeginReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TicketVerificationReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryPaymentResultReq))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderCommitReq))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Request : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteFaultResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteResultResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderExecuteBeginResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TicketVerificationResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryPaymentResultResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderCommitResp))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Responce : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteFaultResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("respCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
                this.RaisePropertyChanged("respCodeMemo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteResultResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("respCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
                this.RaisePropertyChanged("respCodeMemo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteBeginResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("respCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
                this.RaisePropertyChanged("respCodeMemo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TicketVerificationResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private string userMsisdnField;
        
        private string pickupStationCodeField;
        
        private string getOffStationCodeField;
        
        private string singleTicketPriceField;
        
        private string singleTicketNumField;
        
        private string singleTicketTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("respCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
                this.RaisePropertyChanged("respCodeMemo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string userMsisdn {
            get {
                return this.userMsisdnField;
            }
            set {
                this.userMsisdnField = value;
                this.RaisePropertyChanged("userMsisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string pickupStationCode {
            get {
                return this.pickupStationCodeField;
            }
            set {
                this.pickupStationCodeField = value;
                this.RaisePropertyChanged("pickupStationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string getOffStationCode {
            get {
                return this.getOffStationCodeField;
            }
            set {
                this.getOffStationCodeField = value;
                this.RaisePropertyChanged("getOffStationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string singleTicketPrice {
            get {
                return this.singleTicketPriceField;
            }
            set {
                this.singleTicketPriceField = value;
                this.RaisePropertyChanged("singleTicketPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string singleTicketNum {
            get {
                return this.singleTicketNumField;
            }
            set {
                this.singleTicketNumField = value;
                this.RaisePropertyChanged("singleTicketNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string singleTicketType {
            get {
                return this.singleTicketTypeField;
            }
            set {
                this.singleTicketTypeField = value;
                this.RaisePropertyChanged("singleTicketType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryPaymentResultResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        private string paymentDateField;
        
        private string amountField;
        
        private string paymentAccountField;
        
        private string paymentResultField;
        
        private string paymentDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("respCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
                this.RaisePropertyChanged("respCodeMemo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string paymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("paymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string paymentAccount {
            get {
                return this.paymentAccountField;
            }
            set {
                this.paymentAccountField = value;
                this.RaisePropertyChanged("paymentAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string paymentResult {
            get {
                return this.paymentResultField;
            }
            set {
                this.paymentResultField = value;
                this.RaisePropertyChanged("paymentResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string paymentDesc {
            get {
                return this.paymentDescField;
            }
            set {
                this.paymentDescField = value;
                this.RaisePropertyChanged("paymentDesc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderCommitResp : Responce {
        
        private string respCodeField;
        
        private string respCodeMemoField;
        
        private string[] expandAttributeField;
        
        private string partnerNoField;
        
        private string orderNoField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string payTypeField;
        
        private string amountField;
        
        private string accountField;
        
        private string notifyUrlField;
        
        private string merchantCertField;
        
        private int timeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("respCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respCodeMemo {
            get {
                return this.respCodeMemoField;
            }
            set {
                this.respCodeMemoField = value;
                this.RaisePropertyChanged("respCodeMemo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string partnerNo {
            get {
                return this.partnerNoField;
            }
            set {
                this.partnerNoField = value;
                this.RaisePropertyChanged("partnerNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string payType {
            get {
                return this.payTypeField;
            }
            set {
                this.payTypeField = value;
                this.RaisePropertyChanged("payType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string notifyUrl {
            get {
                return this.notifyUrlField;
            }
            set {
                this.notifyUrlField = value;
                this.RaisePropertyChanged("notifyUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string merchantCert {
            get {
                return this.merchantCertField;
            }
            set {
                this.merchantCertField = value;
                this.RaisePropertyChanged("merchantCert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int timeout {
            get {
                return this.timeoutField;
            }
            set {
                this.timeoutField = value;
                this.RaisePropertyChanged("timeout");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteFaultReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private int takeSingleTicketNumField;
        
        private string faultOccurDateField;
        
        private string faultSlipSeqField;
        
        private string erroCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
                this.RaisePropertyChanged("reqSysDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("operationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
                this.RaisePropertyChanged("channelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int takeSingleTicketNum {
            get {
                return this.takeSingleTicketNumField;
            }
            set {
                this.takeSingleTicketNumField = value;
                this.RaisePropertyChanged("takeSingleTicketNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string faultOccurDate {
            get {
                return this.faultOccurDateField;
            }
            set {
                this.faultOccurDateField = value;
                this.RaisePropertyChanged("faultOccurDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string faultSlipSeq {
            get {
                return this.faultSlipSeqField;
            }
            set {
                this.faultSlipSeqField = value;
                this.RaisePropertyChanged("faultSlipSeq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string erroCode {
            get {
                return this.erroCodeField;
            }
            set {
                this.erroCodeField = value;
                this.RaisePropertyChanged("erroCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteResultReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private int takeSingleTicketNumField;
        
        private string takeSingleTicketDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
                this.RaisePropertyChanged("reqSysDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("operationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
                this.RaisePropertyChanged("channelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int takeSingleTicketNum {
            get {
                return this.takeSingleTicketNumField;
            }
            set {
                this.takeSingleTicketNumField = value;
                this.RaisePropertyChanged("takeSingleTicketNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string takeSingleTicketDate {
            get {
                return this.takeSingleTicketDateField;
            }
            set {
                this.takeSingleTicketDateField = value;
                this.RaisePropertyChanged("takeSingleTicketDate");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderExecuteBeginReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
                this.RaisePropertyChanged("reqSysDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("operationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
                this.RaisePropertyChanged("channelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TicketVerificationReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        private string orderTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
                this.RaisePropertyChanged("reqSysDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("operationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
                this.RaisePropertyChanged("channelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string orderToken {
            get {
                return this.orderTokenField;
            }
            set {
                this.orderTokenField = value;
                this.RaisePropertyChanged("orderToken");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryPaymentResultReq : Request {
        
        private string reqSysDateField;
        
        private string operationCodeField;
        
        private string cityCodeField;
        
        private string deviceIdField;
        
        private string channelTypeField;
        
        private string[] expandAttributeField;
        
        private string orderNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string reqSysDate {
            get {
                return this.reqSysDateField;
            }
            set {
                this.reqSysDateField = value;
                this.RaisePropertyChanged("reqSysDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                this.operationCodeField = value;
                this.RaisePropertyChanged("operationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("cityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string channelType {
            get {
                return this.channelTypeField;
            }
            set {
                this.channelTypeField = value;
                this.RaisePropertyChanged("channelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] expandAttribute {
            get {
                return this.expandAttributeField;
            }
            set {
                this.expandAttributeField = value;
                this.RaisePropertyChanged("expandAttribute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface myWebService1SoapChannel : SLEWebServiceTest.SLEWebService.myWebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class myWebService1SoapClient : System.ServiceModel.ClientBase<SLEWebServiceTest.SLEWebService.myWebService1Soap>, SLEWebServiceTest.SLEWebService.myWebService1Soap {
        
        public myWebService1SoapClient() {
        }
        
        public myWebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public myWebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myWebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myWebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SLEWebServiceTest.SLEWebService.OrderCommitResp S1_001(SLEWebServiceTest.SLEWebService.OrderCommitReq orderCommitReq) {
            return base.Channel.S1_001(orderCommitReq);
        }
        
        public SLEWebServiceTest.SLEWebService.QueryPaymentResultResp S1_002(SLEWebServiceTest.SLEWebService.QueryPaymentResultReq queryPaymentResultReq) {
            return base.Channel.S1_002(queryPaymentResultReq);
        }
        
        public SLEWebServiceTest.SLEWebService.TicketVerificationResp S1_006(SLEWebServiceTest.SLEWebService.TicketVerificationReq ticketVerificationReq) {
            return base.Channel.S1_006(ticketVerificationReq);
        }
        
        public SLEWebServiceTest.SLEWebService.OrderExecuteBeginResp S1_003(SLEWebServiceTest.SLEWebService.OrderExecuteBeginReq orderExecuteBeginReq) {
            return base.Channel.S1_003(orderExecuteBeginReq);
        }
        
        public SLEWebServiceTest.SLEWebService.OrderExecuteResultResp S1_004(SLEWebServiceTest.SLEWebService.OrderExecuteResultReq orderExecuteResultReq) {
            return base.Channel.S1_004(orderExecuteResultReq);
        }
        
        public SLEWebServiceTest.SLEWebService.OrderExecuteFaultResp S1_005(SLEWebServiceTest.SLEWebService.OrderExecuteFaultReq orderExecuteFaultReq) {
            return base.Channel.S1_005(orderExecuteFaultReq);
        }
    }
}
